version: '3'

services:
  postgres_main:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  shortener:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres_main
    env_file:
      - .env.docker
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: ['npm', 'run', 'start:setup:dev']

volumes:
  postgres:
